#!/usr/bin/env node

var esprima = require('esprima');

var fs_ = require('fs');

var filename = process.argv[2];
if (!filename) {
    console.log('Usage:');
    console.log('    yaglify foo.js');
    console.log('');
    process.exit(0);
}

var ast = esprima.parse( fs_.readFileSync(filename) );

console.log( JSON.stringify(ast, null, 4) );

//  ---------------------------------------------------------------------------------------------------------------  //

// vim: set filetype=javascript:

